FROM mysql:8.0
COPY replica.cnf /etc/mysql/conf.d/replica.cnf
RUN chmod 644 /etc/mysql/conf.d/replica.cnf
COPY init-replica.sh /docker-entrypoint-initdb.d/01-init-replica.sh
RUN chmod +x /docker-entrypoint-initdb.d/01-init-replica.sh