spring:
  application:
    name: transaction-service

  config:
    import: optional:configserver:http://citicore-config-alb-1654378622.ap-south-1.elb.amazonaws.com

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3306/citicore_transaction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true