spring:
  application:
    name: account-service

  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: localhost
      port: 6379

citicore:
  account:
    min-savings-balance: 1000
    min-current-balance: 5000

  fd:
    default-rate: 6.5
    compounding-frequency: 4
